### ISSUE TITLE
dist_google Error in `[.data.frame`(x, 2) : undefined columns selected

### ISSUE THREAD

**Issue by juanita82** [ropensci/stplanr#182]
I am using coordinates as inputs for dist_google obtained after running gCentroids on a shapefile, 
pkgs = c("sp", "tmap", "rgdal", "rgeos", "stplanr")
lapply(pkgs, library, character.only = T)
download.file(url, "Accra_Neighborhoods_2010.zip")
unzip("Accra_Neighborhoods_2010.zip")

cents = read_shape("Accra_Neighborhoods_2010.shp")
cents = spTransform(x = cents, CRSobj = CRS("+init=epsg:4326"))
cents = gCentroid(cents, byid = T)

route_o<-dist_google(cents@coords[1,], cents@coords[2,])

but I get the error message
Error in `[.data.frame`(x, 2) : undefined columns selected

It also happens when I input the coordinates manually
dist_google(from=c(-17.88438,-83.77098 ), to=c(-17.88438, -83.77098 ))
Error in `[.data.frame`(x, 2) : undefined columns selected

[Accra_Neighborhoods_2010.zip](https://github.com/ropensci/stplanr/files/744170/Accra_Neighborhoods_2010.zip)

**Comment by richardellison** [comment]
The coordinates you used for your manual coordinates are in Antarctica so I wouldn't expect to work anyway.

The issue with the Accra data is that the default mode is "bicycle" but bicycle directions are not available in Ghana. If you change the mode parameter to "walking" or "driving" in the dist_google function call then it works as expected.

I'm going to leave this open for now because we probably should have a more descriptive error message. @Robinlovelace will you have a chance to do this soon?

**Comment by Robinlovelace** [comment]
It's my issue. Thanks for raising this Ana, and sorry for being so slow to reply.
